### ISSUE TITLE
Aggregating status categories

### ISSUE THREAD

**Issue by awoods** [harvard-lts/drs-migration-dashboard#13]
Although there are many states in which a given byte/file/object may be, from the perspective of the consumer of the dashboard, the granularity of the states is not always meaningful. It may be helpful to aggregate some of the status numbers in the donut graphic.

#### Meaningful categories (with nested aggregation)
1. Pending
   - `Pending`
   - `In process`
   - `On hold`
   - `Sensitive`
2. Migrated
   - `Success`
3. Failed Migration
   - `Failure`
   - `Verified failed`
4. Verified
   - `Verified` 

I have left `Unrecoverable` out because these are objects that are scheduled for purge and will not be migrated. I am open to suggestion on how to include (or not include) these objects in the dashboard.

It may be helpful to include the granular categories in the "Numbers" tab. In which case, either colocating or otherwise indicating that `Pending`, `In process`, `On hold`, and `Sensitive` roll up into "Pending" and `Failure` and `Verified failed` roll up into "Failed Migration" in the donut could be helpful.

**Comment by dl-maura** [comment]
@mferrarini did this
